spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
  jpa:
    generate-ddl: true
  kafka:
    consumer:
      group-id: app.1
    bootstrap-servers: localhost:9092

camunda.bpm.admin-user:
  id: admin
  password: admin