spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
  jpa:
    generate-ddl: true

camunda.bpm.admin-user:
  id: admin
  password: admin